//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OroCampo.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OroCampo.WebSite.Resourse", typeof(Resourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εισαγωγή.
        /// </summary>
        public static string button_insert {
            get {
                return ResourceManager.GetString("button_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενέργιες.
        /// </summary>
        public static string column_actions {
            get {
                return ResourceManager.GetString("column_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string column_id {
            get {
                return ResourceManager.GetString("column_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα κατηγορίας.
        /// </summary>
        public static string column_name_category {
            get {
                return ResourceManager.GetString("column_name_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτυχής διαγραφή.
        /// </summary>
        public static string delete_success {
            get {
                return ResourceManager.GetString("delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορίες φωτογραφίας.
        /// </summary>
        public static string photo_category {
            get {
                return ResourceManager.GetString("photo_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείτε να προσθέσετε μία νέα κατηγορία φωτογραφίας ή να διαγράψετε μία υπάρχουσα αν αυτή δεν χρησιμοποιείται..
        /// </summary>
        public static string photo_category_first_text {
            get {
                return ResourceManager.GetString("photo_category_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν κατηγορίες φωτογραφιών.
        /// </summary>
        public static string photo_category_no_categories_available {
            get {
                return ResourceManager.GetString("photo_category_no_categories_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογήστε το όνομα της νέας κατηγορίας και πατήστε το κουμπί &quot;Εισαγωγή&quot; για να την προσθέσετε. Αν τώρα θέλετε να διαγράψετε μια κατηγορία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω..
        /// </summary>
        public static string photo_category_second_text {
            get {
                return ResourceManager.GetString("photo_category_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα νέας φωτογραφίας.
        /// </summary>
        public static string photo_category_text_box_label {
            get {
                return ResourceManager.GetString("photo_category_text_box_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδυναμία διαγραφής. Υπάρχουν φωτογραφίες που χρησιμοποιούν αυτήν την κατηγορία..
        /// </summary>
        public static string photo_category_unable_to_delete_existing_photos {
            get {
                return ResourceManager.GetString("photo_category_unable_to_delete_existing_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορίες προϊόντων.
        /// </summary>
        public static string product_category {
            get {
                return ResourceManager.GetString("product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείτε να προσθέσετε μία νέα κατηγορία προϊόντος ή να διαγράψετε μία υπάρχουσα αν αυτή δεν χρησιμοποιείται..
        /// </summary>
        public static string product_category_first_text {
            get {
                return ResourceManager.GetString("product_category_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν κατηγορίες Προϊόντων.
        /// </summary>
        public static string product_category_no_categories_available {
            get {
                return ResourceManager.GetString("product_category_no_categories_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογήστε το όνομα της νέας κατηγορίας και πατήστε το κουμπί &quot;Εισαγωγή&quot; για να την προσθέσετε. Αν τώρα θέλετε να διαγράψετε μια κατηγορία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω..
        /// </summary>
        public static string product_category_second_text {
            get {
                return ResourceManager.GetString("product_category_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα νέου προϊόντος.
        /// </summary>
        public static string product_category_text_box_label {
            get {
                return ResourceManager.GetString("product_category_text_box_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδυναμία διαγραφής. Υπάρχουν προϊόντα που χρησιμοποιούν αυτήν την κατηγορία..
        /// </summary>
        public static string product_category_unable_to_delete_existing_products {
            get {
                return ResourceManager.GetString("product_category_unable_to_delete_existing_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😢 Κάτι πήγε στραβά.
        /// </summary>
        public static string something_went_wrong {
            get {
                return ResourceManager.GetString("something_went_wrong", resourceCulture);
            }
        }
    }
}
