//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OroCampo.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OroCampo.WebSite.Resourse", typeof(Resourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άρθρα και δημοσιεύσεις .
        /// </summary>
        public static string blog_post {
            get {
                return ResourceManager.GetString("blog_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείται να δημοσιεύσετε ή να διαγράψετε ένα άρθρο.
        /// </summary>
        public static string blog_post_first_text {
            get {
                return ResourceManager.GetString("blog_post_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τίτλος νέας δημοσίευσης .
        /// </summary>
        public static string blog_post_name {
            get {
                return ResourceManager.GetString("blog_post_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν δημοσιευμένα άρθρα..
        /// </summary>
        public static string blog_post_no_available {
            get {
                return ResourceManager.GetString("blog_post_no_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογίστε τον τίτλο της νέας υπηρεσίας, εισάγετε μια περιγραφή για την υπηρεσία και επιλέξτε μια φωτογραφία που αντιπροσοπεύει την υπηρεσία. Τέλος επιλέξτε το κουμπί  &quot;Εισαγωγή&quot; για να την προσθέσεται. Αν τώρα θέλετε να διαγράψετε μια ανάρτηση πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω. Όλα τα πεδία είναι υποχρεωτικά..
        /// </summary>
        public static string blog_post_second_text {
            get {
                return ResourceManager.GetString("blog_post_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κείμενο δημοσίευσης.
        /// </summary>
        public static string blog_post_text {
            get {
                return ResourceManager.GetString("blog_post_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εισαγωγή.
        /// </summary>
        public static string button_insert {
            get {
                return ResourceManager.GetString("button_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακύρωση.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία φωτογραφίας.
        /// </summary>
        public static string category_photo {
            get {
                return ResourceManager.GetString("category_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα νέας κατηγορίας.
        /// </summary>
        public static string category_text_box_label {
            get {
                return ResourceManager.GetString("category_text_box_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενέργιες.
        /// </summary>
        public static string column_actions {
            get {
                return ResourceManager.GetString("column_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εικόνα.
        /// </summary>
        public static string column_icon {
            get {
                return ResourceManager.GetString("column_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string column_id {
            get {
                return ResourceManager.GetString("column_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα κατηγορίας.
        /// </summary>
        public static string column_name_category {
            get {
                return ResourceManager.GetString("column_name_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα προϊόντος.
        /// </summary>
        public static string column_name_product {
            get {
                return ResourceManager.GetString("column_name_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τίτλος δημοσίευσης.
        /// </summary>
        public static string column_title_blog_post {
            get {
                return ResourceManager.GetString("column_title_blog_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τίτλος υπηρεσίας.
        /// </summary>
        public static string column_title_service {
            get {
                return ResourceManager.GetString("column_title_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτυχής διαγραφή.
        /// </summary>
        public static string delete_success {
            get {
                return ResourceManager.GetString("delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή φωτογραφίας.
        /// </summary>
        public static string description_photo {
            get {
                return ResourceManager.GetString("description_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεξεργασία.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προεπισκόπηση εικόνας.
        /// </summary>
        public static string image_preview {
            get {
                return ResourceManager.GetString("image_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/A.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλογή εικόνας.
        /// </summary>
        public static string open_image {
            get {
                return ResourceManager.GetString("open_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φωτογραφίες.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορίες φωτογραφίας.
        /// </summary>
        public static string photo_category {
            get {
                return ResourceManager.GetString("photo_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείτε να προσθέσετε μία νέα κατηγορία φωτογραφίας ή να διαγράψετε μία υπάρχουσα αν αυτή δεν χρησιμοποιείται..
        /// </summary>
        public static string photo_category_first_text {
            get {
                return ResourceManager.GetString("photo_category_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν κατηγορίες φωτογραφιών.
        /// </summary>
        public static string photo_category_no_categories_available {
            get {
                return ResourceManager.GetString("photo_category_no_categories_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογήστε το όνομα της νέας κατηγορίας και πατήστε το κουμπί &quot;Εισαγωγή&quot; για να την προσθέσετε. Αν τώρα θέλετε να διαγράψετε μια κατηγορία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω..
        /// </summary>
        public static string photo_category_second_text {
            get {
                return ResourceManager.GetString("photo_category_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδυναμία διαγραφής. Υπάρχουν φωτογραφίες που χρησιμοποιούν αυτήν την κατηγορία..
        /// </summary>
        public static string photo_category_unable_to_delete_existing_photos {
            get {
                return ResourceManager.GetString("photo_category_unable_to_delete_existing_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείται να προσθέσεται ή να διαγράψετε μια φωτογραφία.
        /// </summary>
        public static string photo_first_text {
            get {
                return ResourceManager.GetString("photo_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εισάγετε μια περιγραφή για την φωτογραφία που θα ανεβάσεται και επιλέξτε την κατηγορία στην οποία ανοικει η φωτογραφία. Τέλος επιλέξτε το κουμπί  &quot;Εισαγωγή&quot; για να την προσθέσεται. Αν τώρα θέλετε να διαγράψετε μια φωτογραφία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω. Όλα τα πεδία είναι υποχρεωτικά. (Αν η κατηγορία που ανοίκει η φωτογραφία δεν υπάρχει ήδη, μπορείτε να την προσθέσεται από την επιλογή &quot;προσθήκη κατηγορίας φωτογραφίας&quot;). .
        /// </summary>
        public static string photo_second_text {
            get {
                return ResourceManager.GetString("photo_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν φωτογραφίες.
        /// </summary>
        public static string photos_no_available {
            get {
                return ResourceManager.GetString("photos_no_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρχείο εικόνας:.
        /// </summary>
        public static string picture_file {
            get {
                return ResourceManager.GetString("picture_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προϊόντα.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία προϊόντος.
        /// </summary>
        public static string product_category {
            get {
                return ResourceManager.GetString("product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείτε να προσθέσετε μία νέα κατηγορία προϊόντος ή να διαγράψετε μία υπάρχουσα αν αυτή δεν χρησιμοποιείται..
        /// </summary>
        public static string product_category_first_text {
            get {
                return ResourceManager.GetString("product_category_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν κατηγορίες Προϊόντων.
        /// </summary>
        public static string product_category_no_categories_available {
            get {
                return ResourceManager.GetString("product_category_no_categories_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογήστε το όνομα της νέας κατηγορίας και πατήστε το κουμπί &quot;Εισαγωγή&quot; για να την προσθέσετε. Αν τώρα θέλετε να διαγράψετε μια κατηγορία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω..
        /// </summary>
        public static string product_category_second_text {
            get {
                return ResourceManager.GetString("product_category_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδυναμία διαγραφής. Υπάρχουν προϊόντα που χρησιμοποιούν αυτήν την κατηγορία..
        /// </summary>
        public static string product_category_unable_to_delete_existing_products {
            get {
                return ResourceManager.GetString("product_category_unable_to_delete_existing_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή προϊόντος.
        /// </summary>
        public static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείται να προσθέσεται ένα νέο προϊόν ή να διαγράψετε κάποιο προϊόν που δεν διατίθεται πλέον από την επιχείρηση..
        /// </summary>
        public static string product_first_text {
            get {
                return ResourceManager.GetString("product_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα νέου προϊόντος.
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν προϊόντα.
        /// </summary>
        public static string product_no_available {
            get {
                return ResourceManager.GetString("product_no_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογίστε το όνομα του νέου προϊόντος, εισάγετε μια περιγραφή για το προϊόν και επιλέξτε την κατηγορία στην οποία ανοικει το προϊόν που θα εισάγετε. Τέλος επιλέξτε το κουμπί  &quot;Εισαγωγή&quot; για να την προσθέσεται. Αν τώρα θέλετε να διαγράψετε ένα προϊόν πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω.Όλα τα πεδία είναι υποχρεωτικά. (Αν η κατηγορία που ανοίκει το προϊόν δεν υπάρχει ήδη, μπορείτε να την προσθέσεται από την επιλογή &quot;προσθήκη κατηγορίας προϊόντος&quot;)..
        /// </summary>
        public static string product_second_text {
            get {
                return ResourceManager.GetString("product_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορίες προϊόντων.
        /// </summary>
        public static string products_categories {
            get {
                return ResourceManager.GetString("products_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπηρεσία.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή υπηρεσίας.
        /// </summary>
        public static string service_description {
            get {
                return ResourceManager.GetString("service_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εδώ μπορείται να προσθέσεται ή να διαγράψετε μια υπηρεσία.
        /// </summary>
        public static string service_first_text {
            get {
                return ResourceManager.GetString("service_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα νέας υπηρεσίας.
        /// </summary>
        public static string service_name {
            get {
                return ResourceManager.GetString("service_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχουν υπηρεσίες.
        /// </summary>
        public static string service_no_available {
            get {
                return ResourceManager.GetString("service_no_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολογίστε τον τίτλο της νέας υπηρεσίας, εισάγετε μια περιγραφή για την υπηρεσία και επιλέξτε μια φωτογραφία που αντιπροσοπεύει την υπηρεσία. Τέλος επιλέξτε το κουμπί  &quot;Εισαγωγή&quot; για να την προσθέσεται. Αν τώρα θέλετε να διαγράψετε μια υπηρεσία πατήστε το κουμπί &quot;Διαγραφή&quot; δίπλα σε κάθε γραμμή κατηγορίας παρακάτω. Όλα τα πεδία είναι υποχρεωτικά. .
        /// </summary>
        public static string service_second_text {
            get {
                return ResourceManager.GetString("service_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😢 Κάτι πήγε στραβά.
        /// </summary>
        public static string something_went_wrong {
            get {
                return ResourceManager.GetString("something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κείμενο νέας δημοσίευσης .
        /// </summary>
        public static string text_blog {
            get {
                return ResourceManager.GetString("text_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενημέρωση.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
    }
}
